import { StrictMode, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Link, Route, Routes, useLocation, useNavigate, useParams } from "react-router-dom";
import "./styles.css";
import "./chat.css";

function Bulldog({ className = "" }: { className?: string }) { return <svg className={`bulldog ${className}`} viewBox="0 0 100 78" role="img" aria-label="Campus Customs bulldog"><path className="dog-ears" d="M20 23 8 12l4 25m68-14 12-11-4 25"/><path className="dog-head" d="M22 27c0-11 12-18 28-18s28 7 28 18v25c0 13-12 20-28 20S22 65 22 52V27Z"/><path className="dog-muzzle" d="M30 43c0-8 8-13 20-13s20 5 20 13v10c0 9-9 15-20 15s-20-6-20-15V43Z"/><circle className="dog-eye" cx="40" cy="34" r="4"/><circle className="dog-eye" cx="60" cy="34" r="4"/><path className="dog-nose" d="m43 47 7-4 7 4-2 7H45Z"/><path className="dog-mouth" d="M50 50v8m-9-1c3 4 15 4 18 0"/><path className="dog-collar" d="M25 61c13 9 37 9 50 0"/><circle className="dog-tag" cx="50" cy="68" r="4"/></svg>; }

type Product = { product_id:string; name:string; garment_type:string; description:string; colors:string[]; search_tags:string[]; image_url:string; price:number; inventory?:{size:string;quantity:number}[] };
const api = (path:string, options?:RequestInit) => fetch(path, { ...options, headers:{"Content-Type":"application/json", ...(options?.headers || {})}, credentials:"include" });
const assetUrl = (path:string) => `${(import.meta.env.VITE_API_BASE_URL || "").replace(/\/$/, "")}${path}`;
function useProducts(){ const [items,setItems]=useState<Product[]>([]); const [error,setError]=useState(""); useEffect(()=>{api("/api/products").then(r=>r.ok?r.json():Promise.reject()).then(setItems).catch(()=>setError("We couldn't load the catalogue right now."));},[]); return {items,error}; }
function Layout(){ const location=useLocation(); const [chat,setChat]=useState(false); const [message,setMessage]=useState(""); const [reply,setReply]=useState(""); const [replyProducts,setReplyProducts]=useState<Product[]>([]); const [sending,setSending]=useState(false); const send=async(e:React.FormEvent)=>{e.preventDefault();if(!message.trim()||sending)return;setSending(true);setReply("");setReplyProducts([]);try{const base=(import.meta.env.VITE_API_BASE_URL||"").replace(/\/$/,"");const productId=location.pathname.startsWith("/products/")?location.pathname.split("/")[2]:null;const r=await fetch(`${base}/chat`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,page_product_id:productId})});const data=await r.json();setReply(r.ok?data.message:(data.detail||"The assistant is unavailable right now."));setReplyProducts(r.ok?(data.products||[]):[]);}catch{setReply("The assistant is unavailable right now.")}finally{setSending(false);setMessage("")}}; return <><header><Link className="logo" to="/"><span>✦</span> CAMPUS CUSTOMS</Link><nav><Link to="/">Home</Link><Link to="/products">Products</Link><Link to="/about">About Us</Link><Link to="/login">Log In</Link><Link className="account" to="/create-account">Create Account</Link></nav></header><main><Routes><Route path="/" element={<Home/>}/><Route path="/products" element={<Products/>}/><Route path="/products/:id" element={<ProductPage/>}/><Route path="/about" element={<About/>}/><Route path="/login" element={<Auth mode="login"/>}/><Route path="/create-account" element={<Auth mode="register"/>}/></Routes></main><button className="chat-button" onClick={()=>setChat(!chat)}>◌ Chat with us</button>{chat&&<div className="chat-panel"><button onClick={()=>setChat(false)}>×</button><h3>Campus Customs chat</h3><p>{reply||"Ask about our collection—we’re happy to help."}</p>{replyProducts.length>0&&<div className="chat-products">{replyProducts.map(p=><Link to={`/products/${p.product_id}`} key={p.product_id} onClick={()=>setChat(false)}><img src={assetUrl(p.image_url)} alt={p.name}/><span>{p.name}<b>${p.price.toFixed(2)}</b></span></Link>)}</div>}<form onSubmit={send}><div className="chat-input"><input value={message} onChange={e=>setMessage(e.target.value)} placeholder={sending?"Thinking…":"Ask us anything…"}/><button disabled={sending}>→</button></div></form></div>}<footer>Campus Customs · Yale spirit, made personal.</footer></> }
function Home(){return <section className="hero"><p className="eyebrow">Yale spirit, your way</p><h1>Wear what<br/><em>feels like Yale.</em></h1><p className="lead">Find the pieces that tell your story—from campus traditions to the people and places that make Yale home.</p><Link className="button" to="/products">Explore the collection <span>→</span></Link><div className="hero-note"><b>Campus Customs</b><br/>A little Yale pride for every kind of day.</div></section>}
function About(){return <section className="text-page"><p className="eyebrow">Our story</p><h1>Made for the<br/><em>Yale community.</em></h1><p>Campus Customs is a place to find the colors, memories, and little traditions that make Yale feel like yours. We bring together everyday staples and meaningful gifts so every Bulldog can carry a piece of campus wherever they go.</p><p>From a first-year sweatshirt to a grandparent’s graduation gift, browse the collection and find something that feels personal.</p><Link className="button" to="/products">Shop Campus Customs →</Link></section>}
function Products(){const {items,error}=useProducts(); const [query,setQuery]=useState(""); const visible=items.filter(p=>`${p.name} ${p.garment_type} ${p.description} ${p.search_tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())); return <section><div className="page-heading"><div><p className="eyebrow">The collection</p><h1>Find your <em>blue.</em></h1></div><p>Pieces for campus, game day, and everywhere Yale takes you.</p></div><input className="catalogue-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search hoodies, Yale, gifts…"/>{error&&<div className="error">{error}</div>}<div className="grid">{visible.map(p=><Link className="product-card" to={`/products/${p.product_id}`} key={p.product_id}><img src={assetUrl(p.image_url)} alt={p.name}/><div><span>{p.garment_type}</span><h3>{p.name}</h3><p>{p.description}</p><b>${p.price.toFixed(2)}</b></div></Link>)}</div></section>}
function ProductPage(){const {id}=useParams(); const [p,setP]=useState<Product|null>(null); useEffect(()=>{api(`/api/products/${id}`).then(r=>r.json()).then(setP)},[id]); if(!p)return <p className="loading">Loading product…</p>; return <section className="detail"><img src={assetUrl(p.image_url)} alt={p.name}/><div><Link className="back" to="/products">← Back to products</Link><p className="eyebrow">{p.garment_type}</p><h1>{p.name}</h1><div className="price">${p.price.toFixed(2)}</div><p>{p.description}</p><div className="tags">{p.colors.map(c=><span key={c}>{c}</span>)}</div><h3>Available sizes</h3><p>{p.inventory?.filter(x=>x.quantity>0).map(x=>x.size).join(" · ") || "Check availability in store"}</p><button className="button">Add to your Yale story</button></div></section>}
function Auth({mode}:{mode:"login"|"register"}){const register=mode==="register"; const [form,setForm]=useState<Record<string,string>>({}); const [message,setMessage]=useState(""); const navigate=useNavigate(); const submit=async(e:React.FormEvent)=>{e.preventDefault();setMessage("");const r=await api(`/api/auth/${register?"register":"login"}`,{method:"POST",body:JSON.stringify(form)});const data=await r.json();if(!r.ok){setMessage(data.detail||"Something went wrong");return}setMessage("You're signed in!");setTimeout(()=>navigate("/"),700)}; return <section className="auth"><p className="eyebrow">Campus Customs</p><h1>{register?"Create your account":"Welcome back"}</h1><p>{register?"Save your favorites and make Yale pride personal.":"Log in to your Campus Customs account."}</p><form onSubmit={submit}>{register&&<><input required placeholder="First name" onChange={e=>setForm({...form,first_name:e.target.value})}/><input required placeholder="Last name" onChange={e=>setForm({...form,last_name:e.target.value})}/></>}<input required type="email" placeholder="Email" onChange={e=>setForm({...form,email:e.target.value})}/><input required type="password" placeholder="Password" onChange={e=>setForm({...form,password:e.target.value})}/>{register&&<input required type="password" placeholder="Confirm password" onChange={e=>setForm({...form,confirm_password:e.target.value})}/>}<button className="button">{register?"Create account":"Log in"}</button></form>{message&&<div className="message">{message}</div>}</section>}
createRoot(document.getElementById("root")!).render(<StrictMode><BrowserRouter><Bulldog className="corner-dog corner-dog-one"/><Bulldog className="corner-dog corner-dog-two"/><Layout/></BrowserRouter></StrictMode>);
